Work-in-progress
farrokhi/adblock-iran pull request #39
Opened 2020-02-12 14:26 UTC by DRSDavidSoft

2021-07-08 11:23 UTC, DRSDavidSoft commented
@farrokhi Sorry this PR has been open for too long. Can you take a look, please?

2021-07-09 07:34 UTC, farrokhi requested changes

2021-07-09 07:34 UTC, farrokhi commented on filter.txt
> +||hexdownload.info/img/ppop.js
this line is duplicate.

2021-07-09 07:34 UTC, farrokhi commented on filter.txt
> +timecity.ir##.banner
Duplicate. See two lines above.

2021-07-09 07:34 UTC, farrokhi commented on filter.txt
> +||snn.ir/files/adv/$image
Already covered by `/files/adv/*` rule

2021-07-09 07:34 UTC, farrokhi commented on filter.txt
>  ! Expires:   4 days
please bump version

2021-07-09 08:59 UTC, DRSDavidSoft commented
@farrokhi Sorry about duplicate lines, bumped the version and updated the checksum.
Any other changes?

2021-07-09 10:08 UTC, farrokhi approved these changes
LGTM. Thanks!

2021-07-09 10:08 UTC, merged